version: '3.4'

services:
  fc.codeflix.catalog.db:
    container_name: catalog_db
    hostname: catalog_db
    image: mysql
    ports :
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

networks:
   service_catalog:
     driver: bridge