version: '3.4'

services:
  fc.codeflix.catalog.db:
    container_name: catalog_db
    hostname: catalog_db
    image: mysql
    ports :
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  rabbitmq:
    container_name: adm_videos_rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=adm_videos
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - 15672:15672
      - 5672:5672

networks:
   service_catalog:
     driver: bridge
